### ISSUE TITLE
Element from which popover was opened above modal

### ISSUE THREAD

**Issue by ricardobarbosahe** [SteffeyDev/react-native-popover-view#43] opened 2019-07-01 14:23 UTC
Hi, is it possible to make the clicked element that was used to trigger the popover visibility  appear "above" the modal background of the popover? At the same level as the popover.
I tried messing around with z-indexes but with no luck.

Thank you.

**Comment by SteffeyDev** [comment] 2019-07-01 16:11
You’ll have to set the mode to `js-modal` to start, then messing with the z-index may yield better results for this.

**Comment by AndrewMorsillo** [comment] 2019-07-01 21:42
There doesn't seem to be a way to set a z-index on the outermost view created by react-native-popover-view when used in js-modal mode. This makes it impossible as far as I can tell to arrange popovers with z-index.

**Comment by SteffeyDev** [comment] 2019-07-01 22:21
It looks like I’m not setting a z-index for the popover, so depending on how RN works setting a z-index high enough may work. You can also control the order that things appear in RN by placement in the code. If the button comes further done in the code than the modal, it should be considered “higher” in the DOM and show above.

**Comment by SteffeyDev** [comment] 2019-07-01 22:23
If you need a control point, feel free to fork the library and try to get it working, I’ll happily take PRs if they are beneficial. Definitely do some testing first though, cause that may not be necessary.

**Comment by AndrewMorsillo** [comment] 2019-07-02 00:06
I was able to work around it by shifting some DOM elements around. I'm not sure if there are any cases where you can't work around it that way but it was a viable solution for me.

**Comment by ricardobarbosahe** [comment] 2019-07-02 10:49
@AndrewMorsillo would you care to explain what you did please? What i am trying to achieve is simply keeping a middle round button on my bottom tab bar above the modal that it triggers. To make the effect that the same button will close the modal again.

I tried the JS version but no luck with the z-index.

**Comment by ricardobarbosahe** [comment] 2019-07-02 10:55
This is what i am doing currently

<img width="365" alt="Screenshot 2019-07-02 at 11 53 58" src="https://user-images.githubusercontent.com/48685853/60507508-38140200-9cc0-11e9-9d20-e48ff9c5302e.png">
<img width="366" alt="Screenshot 2019-07-02 at 11 53 33" src="https://user-images.githubusercontent.com/48685853/60507514-3a765c00-9cc0-11e9-8be5-836b1bb3a68b.png">

**Comment by AndrewMorsillo** [comment] 2019-07-02 15:54
@ricardobarbosahe maybe something like this?

```
<View style={{position: "relative"}}>
     <View style={{zIndex: 1}}> YOUR_POPOVER_HERE </View>
    <View style={{zIndex: 2}}> YOUR_BUTTON_HERE </View>
</View>
```

**Comment by ricardobarbosahe** [comment] 2019-07-02 18:22
@AndrewMorsillo didn't change a thing :/

**Comment by SteffeyDev** [comment] 2019-07-14 21:49
@ricardobarbosahe If you put together a snack or expo of code that should work but doesn't, I can take a look and see if there’s a fix.

**Comment by ricardobarbosahe** [comment] 2019-07-19 14:16
@SteffeyDev 
https://snack.expo.io/@ricardobarbosahe/bottom-bar-popover

I just passed the critical code, the button is inside my bottom tab navigator but the problem appears outside of it as well as you can see on the snack.

Another thing i saw passing the code to the snack is that the position of the popover is different in ios and android, ios being the correct position. Is there a fix for this?

**Comment by SteffeyDev** [comment] 2019-07-20 15:15
Alright, I got it working: https://snack.expo.io/@steffeydev/bottom-bar-popover

Key was using JS Modal and then making sure the popover wasn't hiding behind the other view.  RN Modal forces it to be above everything, but with JS it can easily get hidden if you don't set up the flex box right.

As for the Android issue, I did notice this as well, but it wasn't consistent. If the issue is vertical positioning, try using the verticalOffset prop to adjust it on Android. I’ve had to use it on one of my apps in relation to the android status bar height.

**Comment by SteffeyDev** [comment] 2019-07-20 20:52
@ricardobarbosahe Let me know if you need additional assistance with this issue.  I'm going to close this as an issue because it appears that my library does support this functionality as long as you can figure out how to use it.  Do you mind if I post you snack code or a modified version of your snack code on the README as an example of this functionality?

**Closed by SteffeyDev** 2019-07-20 20:52 UTC
Labels: bug

**Comment by ricardobarbosahe** [comment] 2019-07-20 21:35
I can't see any difference from my snack on your link :S

> Do you mind if I post you snack code or a modified version of your snack code on the README as an example of this functionality?

Yes you can use it no problem, i can clean the code like removing styled-components and stuff if you wish. But first i need to see the changes that i can't see right now xD

**Comment by SteffeyDev** [comment] 2019-07-20 23:36
Oh no it didn’t save! I’m AFK rn but will ping you when I fix it again.

**Comment by SteffeyDev** [comment] 2019-07-21 13:51
@ricardobarbosahe Alright just tested again, appears it did save and is working on iOS and Android.  Not sure what was up with last night.  LMK if it doesn't work for you.

**Comment by ricardobarbosahe** [comment] 2019-07-21 20:14
@SteffeyDev It shows now, perfect! :)

Thank you very much for your help and for your work on this component.
