### ISSUE TITLE
Right-to-left layout issues

### ISSUE THREAD

**Issue by Rohansi** [SteffeyDev/react-native-popover-view#75] opened 2020-07-11 17:01 UTC
**Describe the bug**
My app is only using the centered placement and does not track any elements. Everything works nicely with LTR layout and the popover appears centered properly on the screen. However, when switching to RTL layout mode, the popover now opens partially off screen on the X axis.

RTL layout can be turned on for Android in the developer options.

**Device/Setup Info:**
 - Device: Moto e5 cruise
 - OS: Android 8.0
 - `react-native` version: 0.62
- `react-native-popover-view` version: 3.0.2

**Comment by SteffeyDev** [comment] 2020-07-28 18:59
Duplicate of #75.  Thanks for info, I'll keep tracking this there.

**Closed by SteffeyDev** 2020-07-28 18:59 UTC
