### ISSUE TITLE
The global "__expo" and "Expo" objects will be removed in SDK 41

### ISSUE THREAD

**Issue by erbud** [SteffeyDev/react-native-popover-view#102] opened 2021-04-15 10:30 UTC
**Is your feature request related to a problem? Please describe.**
The global "__expo" and "Expo" objects will be removed in SDK 41.

**Describe the solution you'd like**
Use a module import Constants (expo-constants) rather than a deprecated global API.

**Comment by SteffeyDev** [comment] 2021-04-15 12:27
I don't understand this, you're going to have to be way more specific. AFAIK I don't use any expo-specific code.

**Comment by erbud** [comment] 2021-04-15 20:45
@SteffeyDev when I installing and using react-native-popover-view:

```
<Popover
    from = {(
        <TouchableOpacity>
            <Text> {date.day} </Text>
        </TouchableOpacity>
    )}>
    …
</Popover>
```

The following warning is displayed when activating and displaying the popover:

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals

I'm trying to debug to confirm what causes the warning

Regards.

**Comment by SteffeyDev** [comment] 2021-04-15 23:58
If you remove all the Popovers from your app, but nothing else, does the warning go away?

**Comment by erbud** [comment] 2021-04-16 10:10
@SteffeyDev yes, the warning only is displayed when show and hide the Popover. On tap the component (to show) and on tap outside the Popover (to hide).

**Comment by SteffeyDev** [comment] 2021-04-17 01:56
Well, I just searched my source code to be sure and am not using Expo globals (I don't even have expo as a dependency).  That means that either `react-native-safe-area-view` (my only dependency) is using Expo globals (I am ditching this library soon anyways), Expo is bugging out and giving bad warning, or the issue is in your code or another dependency you are using.  Either way, nothing I can do, so going to close this.  You are free to look through the source code if you would like, it is all here on GitHub for you to review.

**Closed by SteffeyDev** 2021-04-17 01:56 UTC

**Comment by erbud** [comment] 2021-04-19 11:39
@SteffeyDev sorry bro., the warning is triggered by the sentry-expo package …
