### ISSUE TITLE
Subtract verticalOffset from popover height to preserve margins on popover

### ISSUE THREAD

**Issue by outaTiME** [SteffeyDev/react-native-popover-view#49] opened 2019-09-05 23:40 UTC
Hi, 
`verticalOffset` still required on Android on version 2.x when running on expo, and may update the popover height according the vertical offset too (for better experience on large popovers like the image attached) 

here snippet and screenshots, thanks and awesome work !!!

btw: on iOS works as expected.

```js
<TouchableOpacity
  ref={ref => (this._controls_button_ref = ref)}
  style={{
    position: 'absolute',
    top: 0,
    right: 0
  }}
  onPress={this._showControls}
>
  <Text>Button</Text>
</TouchableOpacity>
<Popover
  isVisible={showControls}
  fromView={this._controls_button_ref}
  onRequestClose={this._onPressCancel}
  verticalOffset={
    Platform.OS === 'android' ? -Constants.statusBarHeight : 0
  }
>
  <View>Stuff here</View>
</Popover>
```

![telegram-cloud-photo-size-1-5154761118516881495-y](https://user-images.githubusercontent.com/140472/64390847-d3a55400-d01c-11e9-94c4-6664412159fc.jpg)

**Comment by SteffeyDev** [comment] 2019-09-08 03:37
I’m not entirely sure what the issue is, the popover in the image appears to be working as expected, except maybe slightly offset horizontally. Can you please restate what the issue is exactly, describing the expected behavior and actual behavior of the popover?

**Comment by outaTiME** [comment] 2019-09-09 13:54
Hi @SteffeyDev, the popover height should sustract `verticalOffset` for better vertical alignment on the screen.

And additionally I made the clarification that the `verticaloffset` is still required in Expo.

**Comment by SteffeyDev** [comment] 2019-10-07 02:45
Ah that is amazing clarification, thanks!  I'll do that as part of the next release.

**Comment by SteffeyDev** [comment] 2021-04-19 02:58
In the latest version (4.0.0), the vertical offset is applied before margins, so this should be fixed.  Re-open if it is still an issue in the latest version.

**Closed by SteffeyDev** 2021-04-19 02:58 UTC
Labels: enhancement
