### ISSUE TITLE
Setting 'from' prop from ref to null while open

### ISSUE THREAD

**Issue by kokosin4ik** [SteffeyDev/react-native-popover-view#89] opened 2020-11-11 14:08 UTC
Hi 👋 

I have a strange issue. In my case (Mode.Rn_Modal) i have `from={flag ? anchorRef : null }`. So when my popover is rendered with anchor for some element, there is a case when I want to show popover at the center without anchor and **_without rerender children_**. But now nothing happens when i change the `from` prop in runtime. Only when I have closed and opened it again it appears at the center without acnhor.

Can you help me? Is it a bug or expected behaviour?

**Comment by SteffeyDev** [comment] 2020-11-12 02:06
I believe this is expected behavior, I never intended for the `from` prop to be changed while the popover is open, and most likely don't have any code reacting to the change. However, I can consider this as a feature request if that is indeed what you are looking for.

**Comment by kokosin4ik** [comment] 2020-11-12 07:07
It will be great. We really need such behavior, it will help us a lot.

**Comment by SteffeyDev** [comment] 2022-03-21 03:01
I was able to get this working, this will be included in 5.0

**Closed by SteffeyDev** 2022-03-21 03:01 UTC
Labels: enhancement

**Comment by SteffeyDev** [comment] 2022-03-27 21:11
Version 5.0.0 released, which includes support for this feature
