### ISSUE TITLE
Shadow style not displaying

### ISSUE THREAD

**Issue by SilentChris** [SteffeyDev/react-native-popover-view#15] opened 2018-08-21 21:21 UTC
Running on React Native 0.55.4

I noticed that the default styles for the popover include a box shadow around the view. Unfortunately, this doesn't seem to be displaying. 

It seems that the issue might be a conflict with `Animated.View` and the `boxShadow` styles. If I manually hack it so that the styles get applied to a regular `View` child below the `Animated.View`, the shadow displays as expected.

**Comment by SteffeyDev** [comment] 2018-08-22 15:34
Interesting, can you upload screenshots to show the difference, or submit a PR with your fix?

**Comment by braxtonchristensen** [comment] 2018-10-16 18:10
I also noticed this, I added a package patch to add the shadow but it wouldn't open on android after my attempt, I'll try to look into this some more. If I find a good solution I'll open a PR

**Comment by SteffeyDev** [comment] 2019-04-11 03:11
@braxtonchristensen @SilentChris Did you guys ever get this to work consistently?  I would be happy to merge in some code and test if you have working code in a fork or locally.

**Comment by SilentChris** [comment] 2019-04-12 17:26
I don't think I ever came up with a great solution here. Since we don't use popovers in a lot of places, I just have it switching styles based on `Platform.OS` with iOS getting the drop-shadow styles. I'm still not sure why the existing shadow style doesn't work as expected on the outer `View` container

**Comment by n-kumari** [comment] 2019-04-12 20:47
The issue is there because of `overflow: 'hidden`  in the style `popoverContent`. Removing `overflow:hidden` solves the issue. See snack https://snack.expo.io/@nishakumari/shadow-animated. I have used the same styles as in this library with minor tweaks for easy viewing.

 This, however, is not a solution I would want for the library. 

There is an open issue with React Native https://github.com/facebook/react-native/issues/449 but was closed and moved to ProductPains. 

Please upvote the issue here https://react-native.canny.io/feature-requests/p/shadow-does-not-appear-if-overflow-hidden-is-set-on-ios.
`

**Comment by SteffeyDev** [comment] 2019-04-15 22:07
That's good to know, I do allow a `popoverStyle` prop so it sounds like you can send `{ overflow: 'visible' }` to fix this on a per-instance basis if you would like.

**Comment by SteffeyDev** [comment] 2022-02-24 20:41
For now, I'll probably make it so that `overflow` is set to `visible` if any shadow props are passed in.

**Comment by SteffeyDev** [comment] 2022-03-12 03:46
I made this change, will be released with 4.2.0

**Closed by SteffeyDev** 2022-03-12 03:46 UTC
Labels: enhancement

**Comment by SteffeyDev** [comment] 2022-03-27 21:12
Version 5.0.0 released, which includes many shadow-related fixes and improvements (see https://github.com/SteffeyDev/react-native-popover-view#upgrading)
